{"timestamp":"2025-09-03T19:07:55.043356","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-09-03T19:07:55.044243","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-09-03T19:07:58.215808Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:07:58.216424Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:07:58.218828Z","level":"info","event":"Current task name:fetch_weather","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:07:58.225016Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.830248Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.830824Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py\", line 198, in _new_conn","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.849849Z","level":"error","event":"    sock = connection.create_connection(","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.850449Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.850823Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/connection.py\", line 60, in create_connection","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.851127Z","level":"error","event":"    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.851443Z","level":"error","event":"               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.851806Z","level":"error","event":"  File \"/usr/local/lib/python3.12/socket.py\", line 978, in getaddrinfo","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.852136Z","level":"error","event":"    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.852410Z","level":"error","event":"               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.852754Z","level":"error","event":"socket.gaierror: [Errno -5] No address associated with hostname","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.853053Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.853326Z","level":"error","event":"The above exception was the direct cause of the following exception:","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.853680Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.853980Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.854232Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 787, in urlopen","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.854541Z","level":"error","event":"    response = self._make_request(","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.854945Z","level":"error","event":"               ^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.855269Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 493, in _make_request","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.855598Z","level":"error","event":"    conn.request(","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.855945Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py\", line 494, in request","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.856253Z","level":"error","event":"    self.endheaders()","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.856600Z","level":"error","event":"  File \"/usr/local/lib/python3.12/http/client.py\", line 1333, in endheaders","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.857078Z","level":"error","event":"    self._send_output(message_body, encode_chunked=encode_chunked)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.857490Z","level":"error","event":"  File \"/usr/local/lib/python3.12/http/client.py\", line 1093, in _send_output","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.857837Z","level":"error","event":"    self.send(msg)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.858137Z","level":"error","event":"  File \"/usr/local/lib/python3.12/http/client.py\", line 1037, in send","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.858452Z","level":"error","event":"    self.connect()","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.858758Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py\", line 325, in connect","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.859041Z","level":"error","event":"    self.sock = self._new_conn()","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.859335Z","level":"error","event":"                ^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.859618Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connection.py\", line 205, in _new_conn","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.859955Z","level":"error","event":"    raise NameResolutionError(self.host, self, e) from e","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.860245Z","level":"error","event":"urllib3.exceptions.NameResolutionError: <urllib3.connection.HTTPConnection object at 0x7b1bbd9878f0>: Failed to resolve 'api.openweathermap.org' ([Errno -5] No address associated with hostname)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.860612Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.860922Z","level":"error","event":"The above exception was the direct cause of the following exception:","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.861203Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.861479Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.861788Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py\", line 667, in send","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.862081Z","level":"error","event":"    resp = conn.urlopen(","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.863122Z","level":"error","event":"           ^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.863542Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/connectionpool.py\", line 841, in urlopen","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.864190Z","level":"error","event":"    retries = retries.increment(","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.864717Z","level":"error","event":"              ^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.865098Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/urllib3/util/retry.py\", line 519, in increment","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.865520Z","level":"error","event":"    raise MaxRetryError(_pool, url, reason) from reason  # type: ignore[arg-type]","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.865879Z","level":"error","event":"    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.866288Z","level":"error","event":"urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /geo/1.0/direct?q=cairo&appid=b0cd269e1d75cd93a3a76e2222f451c8 (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7b1bbd9878f0>: Failed to resolve 'api.openweathermap.org' ([Errno -5] No address associated with hostname)\"))","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.866809Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.867121Z","level":"error","event":"During handling of the above exception, another exception occurred:","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.867511Z","level":"error","event":"","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.867815Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.868113Z","level":"error","event":"  File \"/opt/airflow/dags/fetch_weather.py\", line 118, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.868443Z","level":"error","event":"    get_pollution(city_dict)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.868762Z","level":"error","event":"  File \"/opt/airflow/dags/fetch_weather.py\", line 36, in get_pollution","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.869087Z","level":"error","event":"    cities = get_geo(city_dict)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.869389Z","level":"error","event":"             ^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.869681Z","level":"error","event":"  File \"/opt/airflow/dags/fetch_weather.py\", line 22, in get_geo","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.869968Z","level":"error","event":"    city_r = requests.get(f\"http://api.openweathermap.org/geo/1.0/direct?q={city['name']}&appid={apiKey}\")","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.870225Z","level":"error","event":"             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.870476Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py\", line 73, in get","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.870715Z","level":"error","event":"    return request(\"get\", url, params=params, **kwargs)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.870925Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.871183Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/requests/api.py\", line 59, in request","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.871449Z","level":"error","event":"    return session.request(method=method, url=url, **kwargs)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.872093Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.872461Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py\", line 589, in request","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.872802Z","level":"error","event":"    resp = self.send(prep, **send_kwargs)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.873090Z","level":"error","event":"           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.873357Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/requests/sessions.py\", line 703, in send","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.873668Z","level":"error","event":"    r = adapter.send(request, **kwargs)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.874004Z","level":"error","event":"        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.874389Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/requests/adapters.py\", line 700, in send","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.874738Z","level":"error","event":"    raise ConnectionError(e, request=request)","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.875007Z","level":"error","event":"requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.openweathermap.org', port=80): Max retries exceeded with url: /geo/1.0/direct?q=cairo&appid=b0cd269e1d75cd93a3a76e2222f451c8 (Caused by NameResolutionError(\"<urllib3.connection.HTTPConnection object at 0x7b1bbd9878f0>: Failed to resolve 'api.openweathermap.org' ([Errno -5] No address associated with hostname)\"))","chan":"stderr","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.903435","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/fetch_weather.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetchin_cleaning.py","lineno":13,"name":"fetch_weather"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-09-03T19:08:02.905238Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.905664Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.906029Z","level":"info","event":"Task:<Task(PythonOperator): fetch_weather>","chan":"stdout","logger":"task"}
{"timestamp":"2025-09-03T19:08:02.906392Z","level":"info","event":"Failure caused by Command '['python', 'dags/fetch_weather.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
