{"timestamp":"2025-08-21T07:09:27.236578","level":"info","event":"DAG bundles loaded: dags-folder, example_dags","logger":"airflow.dag_processing.bundles.manager.DagBundlesManager"}
{"timestamp":"2025-08-21T07:09:27.237220","level":"info","event":"Filling up the DagBag from /opt/airflow/dags/fetchin_cleaning.py","logger":"airflow.models.dagbag.DagBag"}
{"timestamp":"2025-08-21T07:09:27.297986Z","level":"info","event":"Task instance is in running state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:27.298473Z","level":"info","event":" Previous state of the Task instance: TaskInstanceState.QUEUED","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:27.300612Z","level":"info","event":"Current task name:clean_data","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:27.300950Z","level":"info","event":"Dag name:weather_to_snowflake_pipeline","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.765273Z","level":"error","event":"Traceback (most recent call last):","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.765821Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 184, in <module>","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.769265Z","level":"error","event":"    data_cleaning()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.770533Z","level":"error","event":"  File \"/opt/airflow/dags/cleaning_data.py\", line 127, in data_cleaning","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.773273Z","level":"error","event":"    pollutants_fact_new = pollutants_fact_new.merge(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.773755Z","level":"error","event":"                          ^^^^^^^^^^^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.774123Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py\", line 10487, in merge","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.776041Z","level":"error","event":"    return merge(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.776761Z","level":"error","event":"           ^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.777228Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py\", line 169, in merge","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.777736Z","level":"error","event":"    op = _MergeOperation(","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.778116Z","level":"error","event":"         ^^^^^^^^^^^^^^^^","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.778457Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py\", line 804, in __init__","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.778898Z","level":"error","event":"    self._maybe_coerce_merge_keys()","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.779394Z","level":"error","event":"  File \"/home/airflow/.local/lib/python3.12/site-packages/pandas/core/reshape/merge.py\", line 1483, in _maybe_coerce_merge_keys","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.779722Z","level":"error","event":"    raise ValueError(msg)","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:28.780152Z","level":"error","event":"ValueError: You are trying to merge on datetime64[ns] and object columns for key 'pollution_dt'. If you wish to proceed you should use pd.concat","chan":"stderr","logger":"task"}
{"timestamp":"2025-08-21T07:09:29.003897","level":"error","event":"Task failed with exception","logger":"task","error_detail":[{"exc_type":"CalledProcessError","exc_value":"Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","exc_notes":[],"syntax_error":null,"is_cause":false,"frames":[{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":890,"name":"run"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/task_runner.py","lineno":1177,"name":"_execute_task"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/bases/operator.py","lineno":397,"name":"wrapper"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":217,"name":"execute"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/standard/operators/python.py","lineno":240,"name":"execute_callable"},{"filename":"/home/airflow/.local/lib/python3.12/site-packages/airflow/sdk/execution_time/callback_runner.py","lineno":81,"name":"run"},{"filename":"/opt/airflow/dags/fetchin_cleaning.py","lineno":12,"name":"clean_data"},{"filename":"/usr/local/lib/python3.12/subprocess.py","lineno":571,"name":"run"}],"is_group":false,"exceptions":[]}]}
{"timestamp":"2025-08-21T07:09:29.006192Z","level":"info","event":"Task instance in failure state","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:29.006758Z","level":"info","event":"Task start","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:29.007242Z","level":"info","event":"Task:<Task(PythonOperator): clean_data>","chan":"stdout","logger":"task"}
{"timestamp":"2025-08-21T07:09:29.007619Z","level":"info","event":"Failure caused by Command '['python', 'dags/cleaning_data.py']' returned non-zero exit status 1.","chan":"stdout","logger":"task"}
